import { chromium } from "playwright";
import { spawn } from "node:child_process";
import { createInterface } from "node:readline";
import { createHash } from "node:crypto";
import * as fs from "node:fs/promises";
import * as path from "node:path";
import assert from "node:assert/strict";
import test from "node:test";

const repository = path.resolve(".");
const screenshots = path.join(repository, process.env.MEMOFLOW_TEST_HOTWORDS ? ".runtime/ui-user-hotwords" : ".runtime/ui-previews");

// 以合成输入启动真实HTTP服务，结束后清理整个测试工作区。
test("Edge页面完成双语、词表编辑、上下文校验、凭据保存及任务撤回重建", { timeout: 120_000 }, async (t) => {
  const testRoot = path.join(repository, ".runtime/browser-tests");
  await fs.mkdir(testRoot, { recursive: true });
  await fs.mkdir(screenshots, { recursive: true });
  const root = await fs.mkdtemp(path.join(testRoot, "run-"));
  const externalWords = process.env.MEMOFLOW_TEST_HOTWORDS ? path.resolve(process.env.MEMOFLOW_TEST_HOTWORDS) : null;
  const sourceDigest = externalWords ? createHash("sha256").update(await fs.readFile(externalWords)).digest("hex") : null;
  const previousTemp = { TEMP: process.env.TEMP, TMP: process.env.TMP };
  process.env.TEMP = root;
  process.env.TMP = root;
  const server = spawn(path.join(repository, ".venv/Scripts/python.exe"),
    ["-B", "-X", "utf8", "-m", "tests.browser_server", "--workspace", root],
    { cwd: repository, windowsHide: true, stdio: "pipe" });
  t.after(async () => {
    if (server.exitCode === null && server.signalCode === null) {
      const ended = new Promise<void>(resolve => server.once("exit", () => resolve()));
      server.kill();
      await ended;
    }
    const actual = await fs.realpath(root);
    assert.equal(path.dirname(actual), await fs.realpath(testRoot));
    await fs.rm(actual, { recursive: true });
    if (externalWords) assert.equal(createHash("sha256").update(await fs.readFile(externalWords)).digest("hex"), sourceDigest);
    for (const name of ["TEMP", "TMP"] as const) {
      if (previousTemp[name] === undefined) delete process.env[name];
      else process.env[name] = previousTemp[name];
    }
  });
  const lines = createInterface({ input: server.stdout });
  const connection = await new Promise<{ url: string }>((resolve, reject) => {
    lines.once("line", line => {
      try { resolve(JSON.parse(line) as { url: string }); }
      catch { reject(new Error("本机测试服务返回了无效的启动回执。")); }
      lines.close();
    });
    server.once("error", reject);
    server.once("exit", () => reject(new Error("本机测试服务在就绪前退出。")));
  });
  const origin = new URL(connection.url).origin;
  const browser = await chromium.launch({ channel: 'msedge', headless: true });
  try {
    const context = await browser.newContext({ viewport: { width: 1440, height: 1050 }, locale: 'zh-CN', colorScheme: 'light' });
    const page = await context.newPage();
    const errors: string[] = [], requests: { origin: string; path: string }[] = [];
    const gatewayFailures: string[] = [];
    page.on('pageerror', error => errors.push(error.message));
    page.on('console', message => { if (message.type() === 'error') errors.push(message.text()); });
    page.on('request', request => { const url = new URL(request.url()); requests.push({ origin: url.origin, path: url.pathname }); });
    page.on('response', response => { if (response.status() === 502) gatewayFailures.push(new URL(response.url()).pathname); });
    const sessionResponse = page.waitForResponse(response => new URL(response.url()).pathname === '/api/session');
    await page.goto(connection.url);
    assert.equal((await (await sessionResponse).json()).model, 'qwen-audio-3.1-asr-flash-filetrans');
    await page.getByText('选择音频文件', { exact: true }).waitFor();
    assert.equal(await page.locator('#language_hint').getByText('自动识别', { exact: true }).isVisible(), true);
    await page.screenshot({ path: path.join(screenshots, 'zh-light.png'), animations: 'disabled' });
    await page.emulateMedia({ colorScheme: 'dark' });
    await page.waitForFunction(() => document.documentElement.classList.contains('dark'));
    await page.screenshot({ path: path.join(screenshots, 'zh-dark.png'), animations: 'disabled' });
    await page.locator('.language-select').click();
    await page.getByRole('option', { name: 'English', exact: true }).click();
    await page.locator('.theme-select').click();
    await page.getByRole('option', { name: 'Light', exact: true }).click();
    await page.waitForFunction(() => !document.documentElement.classList.contains('dark'));
    await page.locator('#page-title').click();
    await page.screenshot({ path: path.join(screenshots, 'en-light.png'), animations: 'disabled' });
    await page.locator('.theme-select').click();
    await page.getByRole('option', { name: 'Dark', exact: true }).click();
    assert.equal(await page.locator('html').getAttribute('lang'), 'en');
    assert.equal(await page.locator('html').getAttribute('class'), 'dark');
    await page.locator('#page-title').click();
    await page.screenshot({ path: path.join(screenshots, 'en-dark.png'), animations: 'disabled' });
    await page.getByRole('button', { name: 'Check and preview', exact: true }).click();
    await page.locator('#error-panel').getByText('Choose an audio file.', { exact: true }).waitFor();
    assert.equal(await page.locator('#audio_upload_id').evaluate(element => element.contains(document.activeElement)), true);
    await page.locator('label[for="use-api-key"]').click();
    await page.locator('#api-key-value').fill('fixture-ui-key-not-real');
    await page.route(origin + '/api/save-api-key', route => route.fulfill({ status: 422, contentType: 'application/json',
      body: JSON.stringify({ ok: false, field: 'auth_mode', error: 'Cannot save fixture key.' }) }), { times: 1 });
    const saveKey = page.getByRole('button', { name: 'Save API key', exact: true });
    await saveKey.click();
    await page.locator('#error-panel').getByText('Cannot save fixture key.', { exact: true }).waitFor();
    assert.equal(await saveKey.isEnabled(), true);
    assert.equal(await page.locator('#api-key-value').inputValue(), 'fixture-ui-key-not-real');
    assert.equal(requests.filter(request => request.path === '/api/save-api-key').length, 1);
    await assert.rejects(fs.access(path.join(root, '.asr-transcription/.env')), { code: 'ENOENT' });
    await saveKey.click();
    await page.getByText('API key saved to this working folder.', { exact: true }).waitFor();
    assert.equal(await saveKey.isDisabled(), true);
    assert.ok((await fs.readFile(path.join(root, '.asr-transcription/.env'), 'utf8')).includes('fixture-ui-key-not-real'));
    await assert.rejects(fs.access(path.join(root, '.asr-transcription/.state/jobs')), { code: 'ENOENT' });
    assert.equal(requests.filter(request => ['/api/upload-audio', '/api/validate', '/api/confirm'].includes(request.path)).length, 0);
    await page.locator('#audio_upload_id input[type=file]').setInputFiles(path.join(root, 'fixtures/sample.wav'));
    await page.locator('#audio_upload_id').getByText('Added', { exact: true }).waitFor();
    await page.locator('#language_hint .el-select').click();
    await page.getByRole('option', { name: 'English', exact: true }).click();
    await page.getByRole('button', { name: 'Check and preview', exact: true }).click();
    await page.getByRole('button', { name: 'Save settings', exact: true }).waitFor();
    assert.equal(requests.filter(request => request.path === '/api/save-api-key').length, 2);
    assert.ok((await page.locator('#review').innerText()).includes('mono'));
    await page.locator('label[for="hotwords-enabled"]').click();
    await page.locator('label[for="context-enabled"]').click();
    const download = page.waitForEvent('download');
    await page.getByRole('button', { name: 'Download template', exact: true }).click();
    assert.equal((await download).suggestedFilename(), 'hotwords-template.xlsx');
    const input = '--terms "Kubernetes"\nC:\\voice\\😀 context';
    await page.locator('#context-text').fill(input);
    await page.locator('#hotword_rows input[type=file]').setInputFiles(path.join(root, 'fixtures/invalid.xlsx'));
    await page.locator('#hotword-issues').waitFor();
    assert.ok((await page.locator('#hotword-issues').innerText()).includes('The first row must contain text and weight'));
    assert.ok((await page.locator('#hotword-issues').innerText()).includes('Row 1'));
    assert.equal(await page.locator('#hotword-issues').evaluate(element => document.activeElement === element), true);
    await page.locator('#hotword_rows input[type=file]').setInputFiles(path.join(root, 'fixtures/paged.xlsx'));
    await page.locator('#hotword-62-weight[aria-invalid="true"]').waitFor();
    assert.equal(await page.locator('#hotword-2-text').count(), 0);
    await page.locator('#hotword-62-weight').fill('4');
    await page.getByRole('button', { name: 'Check hotwords', exact: true }).click();
    await page.getByText('Checked: 61 hotwords', { exact: true }).waitFor();
    const validColor = await page.locator('#hotword-62-text').evaluate(element => getComputedStyle(element.closest('tr')!).backgroundColor);
    await page.getByRole('button', { name: 'Delete row 62', exact: true }).click();
    await page.locator('#hotword-52-text').waitFor();
    assert.equal(await page.locator('#hotword-2-text').count(), 0);
    await page.locator('#hotword_rows input[type=file]').setInputFiles(externalWords ?? path.join(root, 'fixtures/invalid-rows.xlsx'));
    const duplicateRows = externalWords ? [2, 3, 4, 5] : [2, 4];
    for (const row of duplicateRows) {
      await page.locator(`#hotword-${row}-text[aria-invalid="true"]`).waitFor();
      assert.ok((await page.locator(`#hotword-${row}-text-errors`).innerText()).length > 0);
    }
    await page.locator('#hotword-3-weight[aria-invalid="true"]').waitFor();
    assert.equal(await page.locator('.hotword-error-row').count(), externalWords ? 4 : 3);
    assert.equal(await page.getByRole('button', { name: /^Delete row \d+$/ }).count(), externalWords ? 4 : 3);
    assert.ok((await page.locator('#hotword-3-weight-errors').innerText()).length > 0);
    const invalidColor = await page.locator('.hotword-error-row').first().evaluate(element => getComputedStyle(element).backgroundColor);
    assert.notEqual(invalidColor, validColor);
    await page.locator('#hotword_rows').screenshot({ path: path.join(screenshots, 'hotwords-en-dark-errors.png'), animations: 'disabled' });
    await page.locator('.theme-select').click();
    await page.getByRole('option', { name: 'Light', exact: true }).click();
    await page.locator('#hotword_rows').screenshot({ path: path.join(screenshots, 'hotwords-en-light-errors.png'), animations: 'disabled' });
    await page.locator('.language-select').click();
    await page.getByRole('option', { name: '简体中文', exact: true }).click();
    await page.getByRole('button', { name: '检查词表', exact: true }).click();
    await page.locator('#hotword-3-weight[aria-invalid="true"]').waitFor();
    await page.locator('#hotword_rows').screenshot({ path: path.join(screenshots, 'hotwords-zh-light-errors.png'), animations: 'disabled' });
    await page.locator('.theme-select').click();
    await page.getByRole('option', { name: '深色', exact: true }).click();
    await page.locator('#hotword_rows').screenshot({ path: path.join(screenshots, 'hotwords-zh-dark-errors.png'), animations: 'disabled' });
    await page.setViewportSize({ width: 390, height: 844 });
    await page.locator('#hotword_rows').scrollIntoViewIfNeeded();
    await page.screenshot({ path: path.join(screenshots, 'mobile-hotwords-dark.png') });
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false);
    await page.setViewportSize({ width: 1440, height: 1050 });
    await page.locator('.language-select').click();
    await page.getByRole('option', { name: 'English', exact: true }).click();
    const validWeight = await page.locator('#hotword-2-weight').inputValue();
    const previousWordChecks = requests.filter(request => request.path === '/api/validate-hotwords').length;
    if (externalWords) {
      for (const row of [3, 4, 5]) await page.getByRole('button', { name: `Delete row ${row}`, exact: true }).click();
    } else {
      await page.locator('#hotword-3-weight').fill(validWeight);
      await page.getByRole('button', { name: 'Delete row 4', exact: true }).click();
    }
    assert.equal(requests.filter(request => request.path === '/api/validate-hotwords').length, previousWordChecks);
    const checked = page.waitForResponse(response => new URL(response.url()).pathname === '/api/validate-hotwords');
    await page.getByRole('button', { name: 'Check hotwords', exact: true }).click();
    const checkedWords = await (await checked).json() as { issues: unknown[]; count: number };
    assert.deepEqual(checkedWords.issues, []);
    assert.equal(checkedWords.count, externalWords ? 1 : 2);
    const hotwordCount = `${checkedWords.count} ${checkedWords.count === 1 ? 'hotword' : 'hotwords'}`;
    await page.getByText(`Checked: ${hotwordCount}`, { exact: true }).waitFor();
    assert.equal(await page.locator('.hotword-error-row').count(), 0);
    await page.locator('#context-text').fill('😀'.repeat(401));
    await page.setViewportSize({ width: 390, height: 844 });
    const checksBeforeContext = requests.filter(request => request.path === '/api/validate').length;
    await page.getByRole('button', { name: 'Check and preview', exact: true }).click();
    await page.locator('#context .el-form-item__error').waitFor();
    assert.match(await page.locator('#context .el-form-item__error').innerText(), /401 characters, 1 over the 400-character limit/);
    assert.equal(await page.locator('#context-text').inputValue(), '😀'.repeat(401));
    assert.equal(await page.locator('#context-text').evaluate(element => document.activeElement === element), true);
    await page.locator('#context').screenshot({ path: path.join(screenshots, 'context-mobile-error.png'), animations: 'disabled' });
    assert.equal(await page.locator('#context').evaluate(element => {
      const error = element.querySelector('.el-form-item__error')!.getBoundingClientRect();
      const footer = element.querySelector('.textarea-footer')!.getBoundingClientRect();
      return error.bottom <= footer.top;
    }), true);
    await page.locator('#context-text').fill(' \n\t');
    await page.getByRole('button', { name: 'Check and preview', exact: true }).click();
    assert.match(await page.locator('#context .el-form-item__error').innerText(), /only whitespace \(3 characters\)/);
    assert.equal(await page.locator('#context-text').inputValue(), ' \n\t');
    assert.equal(requests.filter(request => request.path === '/api/validate').length, checksBeforeContext);
    await page.setViewportSize({ width: 1440, height: 1050 });
    await page.locator('#context-text').fill(input);
    await page.getByRole('button', { name: 'Check and preview', exact: true }).click();
    await page.getByRole('button', { name: 'Save settings', exact: true }).waitFor();
    assert.ok((await page.locator('#review').innerText()).includes(hotwordCount));
    await page.evaluate(() => window.scrollTo(0, 850));
    const stickyTop = await page.locator('#review').evaluate(element => element.getBoundingClientRect().top);
    assert.ok(stickyTop >= 90 && stickyTop <= 105, 'Review panel should remain visible while scrolling');
    await page.locator('.language-select').click();
    await page.getByRole('option', { name: '简体中文', exact: true }).click();
    assert.equal(await page.locator('#context-text').inputValue(), input);
    assert.equal(await page.getByRole('button', { name: '保存设置', exact: true }).count(), 0);
    await page.setViewportSize({ width: 390, height: 844 });
    await page.evaluate(() => window.scrollTo(0, 0));
    await page.screenshot({ path: path.join(screenshots, 'mobile-dark.png') });
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false);
    await page.setViewportSize({ width: 1440, height: 1050 });
    await page.locator('.language-select').click();
    await page.getByRole('option', { name: 'English', exact: true }).click();
    await page.getByRole('button', { name: 'Check and preview', exact: true }).click();
    await page.route(origin + '/api/confirm', route => route.fulfill({ status: 422, contentType: 'application/json',
      body: JSON.stringify({ ok: false, field: 'confirmation', error: 'Settings changed. Check and preview again.' }) }), { times: 1 });
    await page.getByRole('button', { name: 'Save settings', exact: true }).click();
    await page.locator('#error-panel').waitFor();
    assert.equal(await page.locator('#error-panel').evaluate(element => document.activeElement === element), true);
    await page.getByRole('button', { name: 'Check and preview', exact: true }).click();
    await page.getByRole('button', { name: 'Save settings', exact: true }).click();
    await page.locator('#receipt').waitFor();
    await page.getByText('Follow the next steps and progress in Codex.', { exact: true }).waitFor();
    assert.equal(await page.getByText('Your audio has not been sent to Alibaba Cloud.', { exact: true }).count(), 0);
    assert.equal(await page.locator('#api-key-value').count(), 0);
    const files = await fs.readdir(path.join(root, '.asr-transcription/.state/jobs'));
    assert.equal(files.length, 1);
    const configuration = await fs.readFile(path.join(root, '.asr-transcription/.state/jobs', files[0], 'config.json'), 'utf8');
    assert.equal(configuration.includes('fixture-ui-key-not-real'), false);
    const config = JSON.parse(configuration) as { execution_authorized: boolean; enhancement: { context: string }; recognition_options: { language_hints: string[] } };
    assert.equal(config.execution_authorized, false);
    assert.equal(config.enhancement.context, input);
    assert.deepEqual(config.recognition_options.language_hints, ['en']);
    await page.reload();
    await page.locator('#receipt').waitFor();
    assert.equal(await page.locator('html').getAttribute('lang'), 'en');
    assert.equal(await page.locator('html').getAttribute('class'), 'dark');
    let originalRecovery: unknown;
    await page.route(origin + '/api/reopen', async route => {
      const response = await route.fetch();
      assert.equal(response.status(), 200);
      originalRecovery = await response.json();
      await route.fulfill({ status: 502, contentType: 'application/json',
        body: JSON.stringify({ ok: false, error: 'The response was interrupted after the settings were reopened.' }) });
    }, { times: 1 });
    await page.getByRole('button', { name: 'Modify settings', exact: true }).click();
    await page.locator('#error-panel').getByText('The response was interrupted after the settings were reopened.', { exact: true }).waitFor();
    assert.equal(await page.locator('#receipt').isVisible(), true);
    assert.equal(await page.locator('#context-text').count(), 0);
    assert.equal(requests.filter(request => request.path === '/api/reopen').length, 1);
    const stoppedPath = path.join(root, '.asr-transcription/.state/jobs', files[0], 'execution/status.json');
    const stoppedRecord = await fs.readFile(stoppedPath, 'utf8');
    const stopped = JSON.parse(stoppedRecord);
    assert.equal(stopped.status, 'STOPPED');
    assert.equal(stopped.error.code, 'LOCAL_CONFIG_REOPENED');
    assert.equal((await fs.readdir(path.join(root, '.asr-transcription/.state/jobs'))).length, 1);
    const repeatedRecovery = page.waitForResponse(response => new URL(response.url()).pathname === '/api/reopen' && response.status() === 200);
    await page.getByRole('button', { name: 'Modify settings', exact: true }).click();
    assert.deepEqual(await (await repeatedRecovery).json(), originalRecovery);
    await page.locator('#context-text').waitFor();
    assert.equal(await page.locator('#context-text').inputValue(), input);
    assert.equal(await page.locator('#hotword-2-weight').inputValue(), validWeight);
    if (externalWords) {
      assert.equal(await page.locator('#hotword-3-weight').count(), 0);
      assert.equal(await page.locator('#hotword-5-weight').count(), 0);
    } else assert.equal(await page.locator('#hotword-3-weight').inputValue(), validWeight);
    assert.equal(await page.locator('#hotword-4-weight').count(), 0);
    await page.waitForFunction(() => (document.getElementById('api-key-value') as HTMLInputElement)?.value === 'fixture-ui-key-not-real');
    await page.locator('#audio_upload_id').getByText('Added', { exact: true }).waitFor();
    assert.equal(await fs.readFile(stoppedPath, 'utf8'), stoppedRecord);
    assert.equal(requests.filter(request => request.path === '/api/reopen').length, 2);
    const importsBeforeManual = requests.filter(request => request.path === '/api/upload-hotwords').length;
    const deleteRow = page.getByRole('button', { name: /^Delete row \d+$/ });
    while (await deleteRow.count()) await deleteRow.first().click();
    await page.getByRole('button', { name: 'Add row', exact: true }).click();
    await page.locator('#hotword-1-text').fill('TypedTerm');
    await page.locator('#hotword-1-weight').fill('5');
    await page.getByRole('button', { name: 'Check and preview', exact: true }).click();
    await page.getByRole('button', { name: 'Save settings', exact: true }).click();
    await page.locator('#receipt').waitFor();
    assert.equal(requests.filter(request => request.path === '/api/upload-hotwords').length, importsBeforeManual);
    const newFiles = await fs.readdir(path.join(root, '.asr-transcription/.state/jobs'));
    assert.equal(newFiles.length, 2);
    const newId = newFiles.find(value => value !== files[0]);
    assert.ok(newId);
    assert.ok((await page.locator('#receipt').innerText()).includes(newId));
    const rebuilt = JSON.parse(await fs.readFile(path.join(root, '.asr-transcription/.state/jobs', newId, 'config.json'), 'utf8'));
    assert.deepEqual(rebuilt.enhancement.hotwords.vocabulary, { TypedTerm: 5 });
    assert.equal(rebuilt.enhancement.context, input);
    await page.route(origin + '/api/reopen', async route => {
      const response = await route.fetch();
      assert.equal(response.status(), 200);
      await route.fulfill({ status: 502, contentType: 'application/json',
        body: JSON.stringify({ ok: false, error: 'Synthetic interrupted response before refresh.' }) });
    }, { times: 1 });
    await page.getByRole('button', { name: 'Modify settings', exact: true }).click();
    await page.getByText('Synthetic interrupted response before refresh.', { exact: true }).waitFor();
    const reopensBeforeRefresh = requests.filter(request => request.path === '/api/reopen').length;
    await page.reload();
    await page.locator('#context-text').waitFor();
    assert.equal(await page.locator('#context-text').inputValue(), input);
    assert.equal(await page.locator('#hotword-1-text').inputValue(), 'TypedTerm');
    assert.equal(await page.locator('#hotword-1-weight').inputValue(), '5');
    await page.locator('#audio_upload_id').getByText('Added', { exact: true }).waitFor();
    await page.waitForFunction(() => (document.getElementById('api-key-value') as HTMLInputElement)?.value === 'fixture-ui-key-not-real');
    assert.equal(await page.locator('#receipt').count(), 0);
    assert.equal(requests.filter(request => request.path === '/api/reopen').length, reopensBeforeRefresh);
    const storage = await page.evaluate(() => ({ ...localStorage }));
    assert.deepEqual(Object.keys(storage), ['asr-ui-preferences']);
    assert.equal(JSON.stringify(storage).includes('fixture-ui-key-not-real'), false);
    assert.ok(requests.every(request => request.origin === origin));
    assert.equal(requests.filter(request => request.path === '/api/save-api-key').length, 2);
    assert.deepEqual(gatewayFailures, ['/api/reopen', '/api/reopen']);
    const actualErrors = errors.filter(message => !message.includes('status of 422') && !message.includes('status of 502'));
    assert.deepEqual(actualErrors, []);
    await context.close();
  } finally { await browser.close(); }
});
